[tool.poetry]
name = "calendar"
version = "0.1.0"
description = ""
authors = ["Gabe Joseph <gjoseph92@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
reportlab = "^4.0.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
